### ISSUE TITLE
S01E01: community discussion

### ISSUE THREAD

**Issue by majinghe** [lfapac-open-source-evangelist/open-source-topic-discussion#1]
Community is a hot topic in the past few years,  each open source project  has their own community, but it is a challenge that how to make the community grow well and how to avoid some stupid action during the community activity. lfapac  evangelist team will has a discussion about community, the key words will be

* how to name community in China
* how to operate a community
* some stupid action for community operation

Any input idea will be welcomed.

**Comment by lijiangsheng1** [comment]
I think : community (virtual in internet) must be build , not operate. :-)

**Comment by lijiangsheng1** [comment]
Benoît Demil & Xavier Lecocq，"Neither Market nor Hierarchy nor Network: The Emergence of Bazaar Governance.Organization Studies (01708406); 2006, Vol. 27 Issue 10, p1447-1466, 20p

recommend this paper～
